export const apiMap = {
  base: '/api/v2',
  auth: '/auth/',
  changePassword: '/auth/changePassword/',
  logout: '/auth/logout/',
  refresh: '/auth/refresh/',
  getMe: '/user/me/',
  getHistories: '/history/all/',
  getMain: '/main/',
  getMyBonuses: '/metricaData/myBonuses/',
  getHistoryProducts: '/history/products/',
  getProductHistory: '/history/',
  iSpring: '/main/ispring/',
  getSummary: '/metricaData/groupSummary/',
  getSummaryFilters: '/metricaData/groupSummaryFilterSets/',
  getMerchants: '/metricaData/merchants/',
  updateAvatar: '/user/avatar/',

  widgetMainKpiDetails: '/kpi/widgets/mainKpiDetails/',
  widgetMainTarget: '/kpi/widgets/mainTarget/',
  mainWorkProfile: '/main/workProfile/',
  getWidgetsSummary: '/kpi/widgets/summaryTable/',
  rating: '/rating/',
  branches: '/branches/',
  calculation: '/calculation/',
  historyRole: '/user/role_history/',
  historyFilterRole: '/user/role_history_filters/',
  authMAgent: '/auth/magent/',

  getMerchantsFilters: '/metricaData/merchantsFilterSets/',
}
