export { Skeleton } from './ui/Skeleton/Skeleton'
export { SkeletonComment } from './ui/SkeletonComment/SkeletonComment'
export { SkeletonPage } from './ui/SkeletonPage/SkeletonPage'
export { SkeletonProduct } from './ui/SkeletonProduct/SkeletonProduct'
export { SkeletonNews } from './ui/SkeletonNews/SkeletonNews'
export { SkeletonNewsDetail } from './ui/SkeletonNewsDetail/SkeletonNewsDetail'
