import { ProductCardProps } from '../../../entities/product/types/types'

export const catalogProductsMock: ProductCardProps[] = [
  {
    product_Id: 30,
    image: '/tire.jpeg',
    season: { label: 'winter', value: 'winter' },
    average_rating: 4.5,
    comments_count: 3,
    title: 'Vector',
    in_stock: 3,
    price: 3000,
    is_favorite: true,
  },
  {
    product_Id: 31,
    image: '/tire.jpeg',
    season: { label: 'summer', value: 'summer' },
    average_rating: 4.2,
    comments_count: 5,
    title: 'Goodyear Vector 4Seasons',
    in_stock: 5,
    price: 4500,
    is_favorite: false,
  },
  {
    product_Id: 32,
    image: '/tire.jpeg',
    season: { label: 'allSeason', value: 'all_season' },
    average_rating: 4.8,
    comments_count: 8,
    title: 'Continental AllSeason',
    in_stock: 2,
    price: 5200,
    is_favorite: true,
  },
  {
    product_Id: 33,
    image: '/tire.jpeg',
    season: { label: 'winter', value: 'winter' },
    average_rating: 4.6,
    comments_count: 4,
    title: 'Goodyear UltraGrip',
    in_stock: 7,
    price: 3800,
    is_favorite: false,
  },
  {
    product_Id: 34,
    image: '/tire.jpeg',
    season: { label: 'summer', value: 'summer' },
    average_rating: 4.1,
    comments_count: 2,
    title: 'Michelin Pilot Sport',
    in_stock: 10,
    price: 5700,
    is_favorite: true,
  },
  {
    product_Id: 35,
    image: '/tire.jpeg',
    season: { label: 'allSeason', value: 'all_season' },
    average_rating: 4.9,
    comments_count: 12,
    title: 'Bridgestone Weather Control',
    in_stock: 4,
    price: 6000,
    is_favorite: false,
  },
  {
    product_Id: 36,
    image: '/tire.jpeg',
    season: { label: 'winter', value: 'winter' },
    average_rating: 4.7,
    comments_count: 6,
    title: 'Nokian Hakkapeliitta',
    in_stock: 5,
    price: 4800,
    is_favorite: true,
  },
  {
    product_Id: 37,
    image: '/tire.jpeg',
    season: { label: 'summer', value: 'summer' },
    average_rating: 4.3,
    comments_count: 7,
    title: 'Pirelli Cinturato P7',
    in_stock: 6,
    price: 4400,
    is_favorite: false,
  },
  {
    product_Id: 38,
    image: '/tire.jpeg',
    season: { label: 'allSeason', value: 'all_season' },
    average_rating: 4.6,
    comments_count: 9,
    title: 'Yokohama BluEarth',
    in_stock: 3,
    price: 4900,
    is_favorite: true,
  },
  {
    product_Id: 39,
    image: '/tire.jpeg',
    season: { label: 'winter', value: 'winter' },
    average_rating: 4.2,
    comments_count: 5,
    title: 'Hankook Winter i*cept',
    in_stock: 8,
    price: 4100,
    is_favorite: false,
  },
  {
    product_Id: 40,
    image: '/tire.jpeg',
    season: { label: 'summer', value: 'summer' },
    average_rating: 4.8,
    comments_count: 11,
    title: 'Dunlop Sport Maxx',
    in_stock: 4,
    price: 5300,
    is_favorite: true,
  },
  {
    product_Id: 41,
    image: '/tire.jpeg',
    season: { label: 'allSeason', value: 'all_season' },
    average_rating: 4.5,
    comments_count: 6,
    title: 'Firestone Destination',
    in_stock: 7,
    price: 4600,
    is_favorite: false,
  },
]
