import { ProductCardProps } from '../../../entities/product/types/types';

export const catalogProductsMock: ProductCardProps[] = [
  {
    productId: 30,
    productImg: '/tire.jpeg',
    season: 'winter',
    rating: 4.5,
    commentQuantity: 3,
    productTitle: 'Vector',
    inStock: 3,
    price: 3000,
    isFavorite: true,
  },
  {
    productId: 31,
    productImg: '/tire.jpeg',
    season: 'summer',
    rating: 4.2,
    commentQuantity: 5,
    productTitle: 'Goodyear Vector 4Seasons',
    inStock: 5,
    price: 4500,
    isFavorite: false,
  },
  {
    productId: 32,
    productImg: '/tire.jpeg',
    season: 'allSeason',
    rating: 4.8,
    commentQuantity: 8,
    productTitle: 'Continental AllSeason',
    inStock: 2,
    price: 5200,
    isFavorite: true,
  },
  {
    productId: 33,
    productImg: '/tire.jpeg',
    season: 'winter',
    rating: 4.6,
    commentQuantity: 4,
    productTitle: 'Goodyear UltraGrip',
    inStock: 7,
    price: 3800,
    isFavorite: false,
  },
  {
    productId: 34,
    productImg: '/tire.jpeg',
    season: 'summer',
    rating: 4.1,
    commentQuantity: 2,
    productTitle: 'Michelin Pilot Sport',
    inStock: 10,
    price: 5700,
    isFavorite: true,
  },
  {
    productId: 35,
    productImg: '/tire.jpeg',
    season: 'allSeason',
    rating: 4.9,
    commentQuantity: 12,
    productTitle: 'Bridgestone Weather Control',
    inStock: 4,
    price: 6000,
    isFavorite: false,
  },
  {
    productId: 36,
    productImg: '/tire.jpeg',
    season: 'winter',
    rating: 4.7,
    commentQuantity: 6,
    productTitle: 'Nokian Hakkapeliitta',
    inStock: 5,
    price: 4800,
    isFavorite: true,
  },
  {
    productId: 37,
    productImg: '/tire.jpeg',
    season: 'summer',
    rating: 4.3,
    commentQuantity: 7,
    productTitle: 'Pirelli Cinturato P7',
    inStock: 6,
    price: 4400,
    isFavorite: false,
  },
  {
    productId: 38,
    productImg: '/tire.jpeg',
    season: 'allSeason',
    rating: 4.6,
    commentQuantity: 9,
    productTitle: 'Yokohama BluEarth',
    inStock: 3,
    price: 4900,
    isFavorite: true,
  },
  {
    productId: 39,
    productImg: '/tire.jpeg',
    season: 'winter',
    rating: 4.2,
    commentQuantity: 5,
    productTitle: 'Hankook Winter i*cept',
    inStock: 8,
    price: 4100,
    isFavorite: false,
  },
  {
    productId: 40,
    productImg: '/tire.jpeg',
    season: 'summer',
    rating: 4.8,
    commentQuantity: 11,
    productTitle: 'Dunlop Sport Maxx',
    inStock: 4,
    price: 5300,
    isFavorite: true,
  },
  {
    productId: 41,
    productImg: '/tire.jpeg',
    season: 'allSeason',
    rating: 4.5,
    commentQuantity: 6,
    productTitle: 'Firestone Destination',
    inStock: 7,
    price: 4600,
    isFavorite: false,
  },
];

