export const tireFilters = {
  width: [
    '175',
    '185',
    '195',
    '205',
    '215',
    '225',
    '235',
    '245',
    '255',
    '265',
    '275',
    '285',
    '295',
    '305',
  ],
  profile: ['30', '35', '40', '45', '50', '55', '60', '65', '70', '75'],
  diameter: [
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
  ],
  price: {
    min: 2000,
    max: 50000,
  },
  type: ['Легковые', 'Легкогрузовой (LTR)', 'Внедорожник (SUV)'],
  season: ['Зима', 'Лето', 'Всесезонные'],
  condition: ['Только новые'],
  manufacturer: [
    'Michelin',
    'Bridgestone',
    'Continental',
    'Pirelli',
    'Goodyear',
    'Dunlop',
    'Hankook',
    'Nokian',
    'Toyo',
    'Yokohama',
  ],
  discount: ['Да'],
  runflat: ['Да'],
  offroad: ['Да'],
  speedIndex: ['Q', 'R', 'S', 'T', 'H', 'V', 'W', 'Y', 'Z'],
  efficiency: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  wetGrip: ['A', 'B', 'C', 'D', 'E', 'F'],
}
