export const PromotionData = [
  {
    id: 1,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 2,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 3,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 4,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 5,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 6,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 7,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 8,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
  {
    id: 9,
    title: 'Тормозные колодки со скидкой 10%',
    category: ['Диски', 'Шины'],
    expiryDate: '30.09.2021',
    imageUrl: 'src/shared/assets/imgs/noneImage.png',
  },
]
